# Processing parameters
jetR: [0.4]
alphas: [1, 1.5, 2, 3]

# Initial detector-level binnings. Distributions are rebinned via configs before unfolding
n_pt_bins: 195
pt_limits: [5, 200]
n_lambda_bins: 160
lambda_limits: [0, 0.8]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}}'
    pt_bins_reported: [20, 40]
    plot_overlay_list:
      - ['config_R0.4_1', 'config_R0.4_1.5', 'config_R0.4_2', 'config_R0.4_3']
      - ['config_R0.4_1_SD', 'config_R0.4_1.5_SD', 'config_R0.4_2_SD', 'config_R0.4_3_SD']
    max_reg_param: 10

  ############################################################################
  # Different R & alpha configurations
  config_R0.4_1:
    R: 0.4
    alpha: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.20, 0.21, 0.22, 0.23, 0.24,
                     0.25, 0.26, 0.27, 0.28, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.38,
                     0.40, 0.42, 0.44, 0.46, 0.48, 0.55, 0.65, 0.75]
    obs_max_reported: [0.65]
    obs_bins_det: [0, 0.06, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.20, 0.21, 0.22, 0.23, 0.24,
                   0.25, 0.26, 0.27, 0.28, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.38,
                   0.40, 0.42, 0.44, 0.46, 0.48, 0.55, 0.65, 0.75]
    obs_bins_det_sys_binning: [0, 0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.17, 0.19, 0.20, 0.21,
                               0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.30, 0.31, 0.32, 0.33,
                               0.34, 0.35, 0.36, 0.37, 0.39, 0.41, 0.43, 0.45, 
                               0.47, 0.49, 0.56, 0.66, 0.75]
    reg_param:
      0.4: 3

  config_R0.4_1.5:
    R: 0.4
    alpha: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13,
                     0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 
                     0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.34, 0.36, 0.38, 0.42, 0.55, 0.65]
    obs_max_reported: [0.55]
    obs_bins_det: [0, 0.02, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13,
                   0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25,
                   0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.34, 0.36, 0.38, 0.42, 0.55, 0.65]
    obs_bins_det_sys_binning: [0, 0.025, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095, 0.11, 0.12, 0.13,
                               0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25,
                               0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.35, 0.37, 0.39,
                               0.41, 0.43, 0.57, 0.65]
    reg_param:
      0.4: 3

  config_R0.4_2:
    R: 0.4
    alpha: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11,
                     0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24,
                     0.25, 0.26, 0.28, 0.3, 0.35, 0.45, 0.6]
    obs_max_reported: [0.45]
    obs_bins_det: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11,
                   0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24,
                   0.25, 0.26, 0.28, 0.3, 0.35, 0.45, 0.6]
    obs_bins_det_sys_binning: [0, 0.015, 0.025, 0.035, 0.045, 0.055, 0.065, 0.075, 0.085, 0.095, 
                               0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21,
                               0.22, 0.23, 0.24, 0.25, 0.27, 0.29, 0.33, 0.48, 0.6]
    reg_param:
      0.4: 3

  config_R0.4_3:
    R: 0.4
    alpha: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055,
                     0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.11, 0.12, 0.13,
                     0.14, 0.15, 0.16, 0.18, 0.2, 0.3, 0.5]
    obs_max_reported: [0.3]
    obs_bins_det: [0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055,
                   0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.11, 0.12, 0.13,
                   0.14, 0.15, 0.16, 0.18, 0.2, 0.3, 0.5]
    obs_bins_det_sys_binning: [0, 0.002, 0.006, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045,
                               0.5, 0.055, 0.6, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1,
                               0.11, 0.12, 0.13, 0.14, 0.15, 0.17, 0.19, 0.21, 0.33, 0.5]
    reg_param:
      0.4: 3

###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/rstorage/alice/AnalysisResults/HF_ang/AngR04_ptbin1"
roounfold_path: "/home/ezra/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'ang'
do_unfolding: False
force_rebin: False
do_systematics: False
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Preliminary'

# Whether or not to use the previous preliminary result in final results
use_prev_prelim: False

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning, \
#           random_mass, fastsim_generator0, fastsim_generator1]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: ''
POWHEG_main_data: ''
prompt_response: ''
nonprompt_response: ''
prompt_trkeff: ''
nonprompt_trkeff: ''


# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
