jetR: [0.4]
process_observables: ['jet_axis']
observable_list: ['STD-D', 'WTA-D', 'SD-D', 'STD-WTA', 'WTA-SD', 'STD-SD']
track_mass: 0.13957
track_random_mass: False
IsFiducialCut: True
IsCustomSelectionCuts: True
IsSpecialLowpTCuts: True
sd_zcut: 0.2
sd_beta: 0
Is_treff_sys: False

# For extra verbose output in some functions
debug_level: 0


jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0


###############################################################################
# Rebinning and unfolding parameters/configurations for EEC observables
jet_axis:

    common_settings:
        xtitle: '#DeltaR'
        ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#DeltaR}'

    # Different alpha configurations with SoftDrop
    config_STD-D_1:
        name: "STD-D" #"jet_axis"
        axis: STD-D #, "WTA-D", "SD-D", "STD-SD", "WTA-SD", "STD-WTA"] #STD-D, WTA-D, SD-D, STD-SD, WTA-SD, STD-WTA
        obs_bins: [-0.05, 0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.105, 0.11, 0.115, 0.12, 0.125, 0.13, 0.135, 0.14, 0.145, 0.15, 0.155, 0.16, 0.165, 0.17, 0.175, 0.18, 0.185, 0.19, 0.195, 0.2, 0.205, 0.21, 0.215, 0.22, 0.225, 0.23, 0.235, 0.24, 0.245, 0.25, 0.255, 0.26, 0.265, 0.27, 0.275, 0.28, 0.285, 0.29, 0.295, 0.3, 0.305, 0.31, 0.315, 0.32, 0.325, 0.33, 0.335, 0.34, 0.345, 0.35, 0.355, 0.36, 0.365, 0.37, 0.375, 0.38, 0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415, 0.42, 0.425, 0.43, 0.435, 0.44, 0.445, 0.45, 0.455, 0.46, 0.465, 0.47, 0.475, 0.48, 0.485, 0.49, 0.495, 0.5] #[0, 0.01, 0.03, 0.05, 0.12]
        
    config_WTA-D_1:
        name: "WTA-D"
        axis: WTA-D 
        obs_bins: [-0.05, 0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.105, 0.11, 0.115, 0.12, 0.125, 0.13, 0.135, 0.14, 0.145, 0.15, 0.155, 0.16, 0.165, 0.17, 0.175, 0.18, 0.185, 0.19, 0.195, 0.2, 0.205, 0.21, 0.215, 0.22, 0.225, 0.23, 0.235, 0.24, 0.245, 0.25, 0.255, 0.26, 0.265, 0.27, 0.275, 0.28, 0.285, 0.29, 0.295, 0.3, 0.305, 0.31, 0.315, 0.32, 0.325, 0.33, 0.335, 0.34, 0.345, 0.35, 0.355, 0.36, 0.365, 0.37, 0.375, 0.38, 0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415, 0.42, 0.425, 0.43, 0.435, 0.44, 0.445, 0.45, 0.455, 0.46, 0.465, 0.47, 0.475, 0.48, 0.485, 0.49, 0.495, 0.5] #[0, 0.005, 0.4]

    config_SD-D_1:
        name: "SD-D"
        axis: SD-D 
        obs_bins: [-0.05, 0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.105, 0.11, 0.115, 0.12, 0.125, 0.13, 0.135, 0.14, 0.145, 0.15, 0.155, 0.16, 0.165, 0.17, 0.175, 0.18, 0.185, 0.19, 0.195, 0.2, 0.205, 0.21, 0.215, 0.22, 0.225, 0.23, 0.235, 0.24, 0.245, 0.25, 0.255, 0.26, 0.265, 0.27, 0.275, 0.28, 0.285, 0.29, 0.295, 0.3, 0.305, 0.31, 0.315, 0.32, 0.325, 0.33, 0.335, 0.34, 0.345, 0.35, 0.355, 0.36, 0.365, 0.37, 0.375, 0.38, 0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415, 0.42, 0.425, 0.43, 0.435, 0.44, 0.445, 0.45, 0.455, 0.46, 0.465, 0.47, 0.475, 0.48, 0.485, 0.49, 0.495, 0.5] #[-0.05, 0, 0.05, 0.09, 0.15]
        SoftDrop:
            zcut: 0.2
            beta: 0
    
    config_STD-WTA_1:
        name: "STD-WTA"
        axis: STD-WTA 
        obs_bins: [-0.05, 0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.105, 0.11, 0.115, 0.12, 0.125, 0.13, 0.135, 0.14, 0.145, 0.15, 0.155, 0.16, 0.165, 0.17, 0.175, 0.18, 0.185, 0.19, 0.195, 0.2, 0.205, 0.21, 0.215, 0.22, 0.225, 0.23, 0.235, 0.24, 0.245, 0.25, 0.255, 0.26, 0.265, 0.27, 0.275, 0.28, 0.285, 0.29, 0.295, 0.3, 0.305, 0.31, 0.315, 0.32, 0.325, 0.33, 0.335, 0.34, 0.345, 0.35, 0.355, 0.36, 0.365, 0.37, 0.375, 0.38, 0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415, 0.42, 0.425, 0.43, 0.435, 0.44, 0.445, 0.45, 0.455, 0.46, 0.465, 0.47, 0.475, 0.48, 0.485, 0.49, 0.495, 0.5] #[0, 0.01, 0.03, 0.05, 0.12]

    config_WTA-SD_1:
        name: "WTA-SD"
        axis: WTA-SD 
        obs_bins: [-0.05, 0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.105, 0.11, 0.115, 0.12, 0.125, 0.13, 0.135, 0.14, 0.145, 0.15, 0.155, 0.16, 0.165, 0.17, 0.175, 0.18, 0.185, 0.19, 0.195, 0.2, 0.205, 0.21, 0.215, 0.22, 0.225, 0.23, 0.235, 0.24, 0.245, 0.25, 0.255, 0.26, 0.265, 0.27, 0.275, 0.28, 0.285, 0.29, 0.295, 0.3, 0.305, 0.31, 0.315, 0.32, 0.325, 0.33, 0.335, 0.34, 0.345, 0.35, 0.355, 0.36, 0.365, 0.37, 0.375, 0.38, 0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415, 0.42, 0.425, 0.43, 0.435, 0.44, 0.445, 0.45, 0.455, 0.46, 0.465, 0.47, 0.475, 0.48, 0.485, 0.49, 0.495, 0.5] #[-0.05, 0, 0.05, 0.09, 0.15]
        SoftDrop:
            zcut: 0.2
            beta: 0
    
    config_STD-SD_1:
        name: "STD-SD"
        axis: STD-SD 
        obs_bins: [-0.05, 0.0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06, 0.065, 0.07, 0.075, 0.08, 0.085, 0.09, 0.095, 0.1, 0.105, 0.11, 0.115, 0.12, 0.125, 0.13, 0.135, 0.14, 0.145, 0.15, 0.155, 0.16, 0.165, 0.17, 0.175, 0.18, 0.185, 0.19, 0.195, 0.2, 0.205, 0.21, 0.215, 0.22, 0.225, 0.23, 0.235, 0.24, 0.245, 0.25, 0.255, 0.26, 0.265, 0.27, 0.275, 0.28, 0.285, 0.29, 0.295, 0.3, 0.305, 0.31, 0.315, 0.32, 0.325, 0.33, 0.335, 0.34, 0.345, 0.35, 0.355, 0.36, 0.365, 0.37, 0.375, 0.38, 0.385, 0.39, 0.395, 0.4, 0.405, 0.41, 0.415, 0.42, 0.425, 0.43, 0.435, 0.44, 0.445, 0.45, 0.455, 0.46, 0.465, 0.47, 0.475, 0.48, 0.485, 0.49, 0.495, 0.5] #[-0.05, 0, 0.005, 0.035, 0.07]
        SoftDrop:
            zcut: 0.2
            beta: 0

    # config_WTA-D_2:
    #     name: "WTA-D"
    #     axis: WTA-D 
    #     obs_bins: [0, 0.005]
    


# SD-D:
#     common_settings:
#         xtitle: '#DeltaR'
#         ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#DeltaR}'
#     config_R0.4_SD-D:
#         name: "SD-D" #"jet_axis"
#         R: 0.4
#         alpha: 3
#         axis: "SD-D" #, "WTA-D", "SD-D", "STD-SD", "WTA-SD", "STD-WTA"] #STD-D, WTA-D, SD-D, STD-SD, WTA-SD, STD-WTA
#         pt_bins:  [5, 7, 10, 20, 50]
#         obs_bins: [0, 0.01, 0.02, 0.03, 0.05, 0.075, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4] #[0, 0.01, 0.03, 0.05, 0.12, 0.25]
#         obs_max_reported: [0.4]
#         SoftDrop:
#             zcut: 0.2
#             beta: 0

# jet_axis:

#     common_settings:
#         xtitle: '#DeltaR'
#         ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#DeltaR}'

#     # Different alpha configurations with SoftDrop
#     config_R0.4_STD-D:
#         name: "STD-D" #"jet_axis"
#         axis: STD-D #, "WTA-D", "SD-D", "STD-SD", "WTA-SD", "STD-WTA"] #STD-D, WTA-D, SD-D, STD-SD, WTA-SD, STD-WTA

#     config_R0.4_SD-D:
#         name: "SD-D" #"jet_axis"
#         R: 0.4
#         alpha: 3
#         axis: "SD-D" #, "WTA-D", "SD-D", "STD-SD", "WTA-SD", "STD-WTA"] #STD-D, WTA-D, SD-D, STD-SD, WTA-SD, STD-WTA
#         pt_bins:  [5, 7, 10, 20, 50]
#         obs_bins: [0, 0.01, 0.02, 0.03, 0.05, 0.075, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4] #[0, 0.01, 0.03, 0.05, 0.12, 0.25]
#         obs_max_reported: [0.4]
#         SoftDrop:
#             zcut: 0.2
#             beta: 0

###############################################################################


analysisD0:
        pt_cand_binning:
                sel_an_binmin: [2,3,4,5,6,7,8,10,12,16,24]
                sel_an_binmax: [3,4,5,6,7,8,10,12,16,24,36]
        bitmap_sel:
                var_name: cand_type
                var_isstd: isstd
                var_ismcsignal: ismcsignal
                var_ismcprompt: ismcprompt
                var_ismcfd: ismcfd
                var_ismcbkg: ismcbkg
                var_ismcrefl: ismcrefl
                isstd: [[0],[]]
                ismcsignal: [[1],[5]]
                ismcprompt: [[1,3],[5]]
                ismcfd: [[1,4],[5]]
                ismcbkg: [[2],[]]
                ismcrefl: [[5],[]]

        
        cuts:
                default:
                        - "pt_cand >= 2 and pt_cand < 3 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.8 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -30000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 5."
                        - "pt_cand >= 3 and pt_cand < 4 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.8 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -30000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 5."
                        - "pt_cand >= 4 and pt_cand < 5 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.8 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -15000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 5."
                        - "pt_cand >= 5 and pt_cand < 6 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.8 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -10000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 4."
                        - "pt_cand >= 6 and pt_cand < 7 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.8 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -8000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 4."
                        - "pt_cand >= 7 and pt_cand < 8 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.8 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -8000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 4."
                        - "pt_cand >= 8 and pt_cand < 10 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.9 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -5000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 3."
                        - "pt_cand >= 10 and pt_cand < 12 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 0.9 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= -5000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 3."
                        - "pt_cand >= 12 and pt_cand < 16 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 1.0 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= 10000.e-8 and cos_p >= 0.95 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 3."
                        - "pt_cand >= 16 and pt_cand < 24 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 1.0 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= 10000.e-8 and cos_p >= 0.90 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 3."
                        - "pt_cand >= 24 and pt_cand < 36 and abs(inv_mass - 1.864) <= 0.400 and dca <= 300.e-4 and abs(cos_t_star) <= 1.0 and pt_prong1 >= 0.7 and pt_prong0 >= 0.7 and abs(imp_par_prong1) <= 1000.e-4 and abs(imp_par_prong0) <= 1000.e-4 and imp_par_prod <= 10000.e-8 and cos_p >= 0.90 and abs(cos_p_xy) >= 0. and norm_dl_xy >= 3."