# Processing parameters
jetR: [0.4]
betas: [1]
jet_range: [5,50]
# Initial detector-level binnings. Distributions are rebinned via configs before unfolding
n_pt_bins: 195
pt_limits: [5, 200]
n_lambda_bins: 160
lambda_limits: [0, 0.8]
n_rap_bins: 20            # just for fun, look at lambda distribution vs rapidity
rap_limits: [-0.5, 0.5]
branching_ratio: 3.95e-2
p_nevents: 7.98356e8
xsection_inel: 50.87
fRebinMass: 1
fMassRange: [1.72, 2.01]
fsigmaSignal: 2
jetptbinsMeasN: 10
fDmass: 1.864
fDsigma: 0.010
fsigmaBkg: [-8, -4, 4, 8]
fbkgtype: 0 # kExpo=0, kLin=1, kPol2=2, kNoBk=3, kPow=4, kPowEx=5
fUseRefl: False #True
use_MC_gauss_info: False`
isRefSys: False
refScale: -1.5
jetptbinsMeasA: [2, 3, 4, 5, 6, 8, 10, 14, 20, 30, 50]
fptbinsJetFinalN: 4

jetptbinsFinalA: [5, 7, 10, 20, 50]
ptbinsDN: 11
ptbinsDA: [2, 3, 4, 5, 6, 7, 8, 10, 12, 16, 20, 36]
pt_dmeson_cut: [2, 3, 5, 12]
obs_bins: [0.0,0.005,0.01,0.02,0.04,0.06,0.1] #,0.32,0.4,0.49,0.59,0.7] 
  #[0.0,0.01,0.03,0.05,0.07,0.1,0.14,0.2]  #[0.0,0.01,0.03,0.05,0.07,0.1,0.14,0.2,0.27,0.32,0.4,0.49,0.59,0.7] 
#[0.0,0.01,0.02,0.03,0.04,0.05,0.06,0.08,0.1,0.12,0.14,0.16,0.18,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7]
# For extra verbose output in some functions
debug_level: 0

process_observables: ['jet_axis']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# SoftDrop setting (current same for all SD plots)
sd_zcut: 0.2    # multiplier
sd_beta: 0      # exponent on (deltaR / R)

#sparse
hsparse_jet: ["STD_SD"] #, "WTA_D0", "SD_D0", "STD_SD", "STD_WTA", "WTA_SD"]
  # "hsparse_R0.4_SD-D", "hsparse_R0.4_WTA-SD",
  #            "hsparse_R0.4_STD-WTA", "hsparse_R0.4_STD-SD"] 

###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
jet_axis:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}}'
    pt_bins_reported: [10, 20]
    plot_overlay_list:
      - ['config_R0.4_1']
    max_reg_param: 10

  ############################################################################
  # Different R & beta configurations

  config_R0.4_1:
    R: 0.4
    alpha: 1
    axis: 1
    pt_bins_truth:  [5, 7, 10, 20, 50]
    pt_bins_det: [5, 7, 10, 20, 50]
    pt_bins_det_sys_truncation: [5, 7, 10, 20, 50]
    obs_bins_truth: [0.0,0.005,0.01,0.02,0.04,0.06,0.01] #,0.32,0.4,0.49,0.59,0.7]
    obs_max_reported: [0.4]
    obs_bins_det: [0.0,0.005,0.01,0.02,0.4,0.06,0.1] #,0.32,0.4,0.49,0.59,0.7]
    obs_bins_det_sys_binning: [0, 0.05, 0.07, 0.09, 0.11, 
                               0.14, 0.15, 0.17, 0.19, 0.20,  
                               0.21, 0.22, 0.23, 0.24, 0.25, 
                               0.26, 0.27, 0.28, 0.30, 0.31, 
                               0.32, 0.33, 0.34, 0.35, 0.36, 
                               0.37, 0.39, 0.41, 0.43, 0.45, 
                               0.47, 0.49, 0.56, 0.66, 0.75]
    reg_param:
      0.4: 3

  
###############################################################################
# Theory comparison parameters
do_theory_comp: False




###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/global/cfs/cdirs/alice/eyeats/mypyjetty/pyjetty/pyjetty/alihfjets/dev/hfjet/process/user/hf_jetaxes/std-sd"
output_dir_fd: "/global/cfs/cdirs/alice/eyeats/mypyjetty/pyjetty/pyjetty/alihfjets/dev/hfjet/process/user/hf_jetaxes/std-sd"
rebin_theory_response: False
roounfold_path: "/global/cfs/cdirs/alice/eyeats/mypyjetty/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'jet_axis'
do_unfolding: True
force_rebin: False
do_systematics: False
do_plot_final_result: False
do_plot_performance: False
figure_approval_status: 'Preliminary'

# Whether or not to use the previous preliminary result in final results
use_prev_prelim: False


systematics_list:
  - main
  #- trkeff
  #- prior1
  #- prior2
  #- truncation
  #- binning
  #- random_mass
  #- fastsim_generator0
  #- fastsim_generator1

# Paths to processing output, to be used for unfolding
#default 1409411
main_rawdatafile: '/global/cfs/cdirs/alice/eyeats/AliceAnalyses/ResultsFromHiccup/1409411/AnalysisResultsFinal.root'
#default tracking eff = 1459581
#variaiton = 1358441
main_data_simulation: '/global/cfs/cdirs/alice/eyeats/AliceAnalyses/ResultsFromHiccup/1459581/AnalysisResultsFinal.root'
main_data: '/global/cfs/cdirs/alice/eyeats/mypyjetty/pyjetty/pyjetty/alihfjets/dev/hfjet/process/user/hf_jetaxes/std-sd'
main_feeddown_simulation: '/global/cfs/cdirs/alice/eyeats/mypyjetty/pyjetty/pyjetty/alihfjets/dev/hfjet/process/user/hf_jetaxes/rootfiles/main_feeddown_simulation/trees_powheg+pythia8+evtgen_beauty.root'
main_charm_simulation: ''
#default 1459581
main_response: '/global/cfs/cdirs/alice/eyeats/AliceAnalyses/ResultsFromHiccup/1459581/AnalysisResultsFinal.root'
main_efffile: '/global/cfs/cdirs/alice/eyeats/mypyjetty/pyjetty/pyjetty/alihfjets/dev/hfjet/process/user/hf_jetaxes/rootfiles/D0JetRecoEff.root'
main_nonprompt_kinematic_efffile: ''
reflection_template: ['/global/cfs/cdirs/alice/eyeats/mypyjetty/pyjetty/pyjetty/alihfjets/dev/hfjet/process/user/hf_jetaxes/rootfiles/ReflectionTemplate_10_20.root']

trkeff_response: ''
randmass_data: ''
randmass_response: ''
fastsim_response: ['',
                   '']

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
